[package]
name = "cloudray-agent"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
license = "MIT"
repository = "https://github.com/cloudray-io/cloudray-agent"

[dependencies]
anyhow = "1.0.97"
bytes = "1.10.1"
clap = { version = "4.5.32", features = ["derive", "env"] }
daemonize = "0.5.0"
futures = "0.3.31"
prost = "0.13.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
semver = "1.0.25"
reqwest = "0.12.15"
rand = "0.9.0"
webterm-core = "0.2.5"
hostname = "0.4.0"
mac_address = "1.1.8"
log = "0.4.26"

[build-dependencies]
prost-build = "0.13.5"
